fix: give wrapped_raw_expression_tree_walker_impl external linkage (#49)
I noticed builds off pgdog’s main branch head were failing on my **macOS
machine** (verified macOS 14 and 26) with an error:

  ```        Undefined symbols for architecture arm64:
            "_wrapped_raw_expression_tree_walker_impl", referenced from:
pg_raw_parse::walk::walk_node_cb::h7ecfbd05850c73d7 in
pgdog_primary_only_tables.46rse1j3369ehutv4hr80k4jo.0eh7r6h.rcgu.o
pg_raw_parse::walk::walk_expression_tree_inner::h033b7725d10cdb34 in
pgdog_primary_only_tables.46rse1j3369ehutv4hr80k4jo.0eh7r6h.rcgu.o
          ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
```

It seems this was introduced when we started using the new parser in https://github.com/pgdogdev/pgdog/pull/1324, and wasn’t caught in main on pgdog as the macOS CI (for releases) hadn’t been run yet in the last few days.

---

So.. what’s causing this error?

The helpers in wrapper.h are static inline (Rust can’t link them directly). bindgen normally would generate a public forwarding function for each and point Rust at it via the #[link_name] attribute. 

`wrapped_raw_expression_tree_walker_impl` is unique as it’s the only one marked C-unwind (the only one taking a Rust callback, and unwinding across extern C is undefined behavior). 

Bindgen doesn’t recognize C-unwind, so it uses #[link_name] to write the raw symbol instead of guessing the proper mangling (see this code: https://docs.rs/bindgen/0.72.1/src/bindgen/codegen/mod.rs.html#5935-5947). With that attribute spoken for, it entirely skips generating the forwarder (thus, the binding points at a symbol that never gets created).

Linux works fine since the names match (bindgen compares, sees match, generates forwarder). **macOS has a leading underscore which makes them differ, and forces that ABI check, leading into this mess.**

---

Fixed via giving the function external linkage instead of relying on the forwarder.